setting:
  binWidth: 25  # Width of the grey level bins for intensity discretization
  
imageType:
  Original: {}  # Extract features from the original images specified in the CSV

# Feature classes to include in the extraction
featureClass:
  firstorder: []  # Extract all first-order statistics features
  shape: []  # Extract all shape-based features
  glcm: []  # Extract all features from the Grey Level Co-occurrence Matrix (GLCM)
  glrlm: []  # Extract all features from the Grey Level Run Length Matrix (GLRLM)
  glszm: []  # Extract all features from the Grey Level Size Zone Matrix (GLSZM)
  gldm: []  # Extract all features from the Grey Level Dependence Matrix (GLDM)
  ngtdm: []  # Extract all features from the Neighbourhood Grey Tone Difference Matrix (NGTDM)
